TRUNCATE TABLE candidat RESTART IDENTITY CASCADE;
TRUNCATE TABLE matiere RESTART IDENTITY CASCADE;
TRUNCATE TABLE prof RESTART IDENTITY CASCADE;
TRUNCATE TABLE signe RESTART IDENTITY CASCADE;
TRUNCATE TABLE action RESTART IDENTITY CASCADE;
TRUNCATE TABLE note RESTART IDENTITY CASCADE;
TRUNCATE TABLE paramettre RESTART IDENTITY CASCADE;
-- vita